CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) not NULL,
    login varchar(50) not NULL,
    name varchar(50) not NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS films (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not NULL,
    description varchar(200),
    duration int not NULL,
    reliesDate date
);

CREATE TABLE IF NOT EXISTS reiting (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reiting varchar
);

CREATE TABLE IF NOT EXISTS reiting_film (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id int REFERENCES films(id),
    reiting_id int REFERENCES reiting(id)
);

CREATE TABLE IF NOT EXISTS genre (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar
);

CREATE TABLE IF NOT EXISTS likes (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_like_id int REFERENCES users(id),
    film_like_id int REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS friends (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES users(id),
    friends_id int REFERENCES users(id),
    status varchar(50)
);

CREATE TABLE IF NOT EXISTS film_genre (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id int REFERENCES genre(id),
    film_id int REFERENCES films(id)
);